# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('addrLine1', models.CharField(max_length=100)),
                ('addrLine2', models.CharField(max_length=100, verbose_name='')),
                ('postCode', models.CharField(max_length=20, verbose_name='')),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120, verbose_name='')),
                ('website', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcareweb.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name=0)),
                ('userEmail', models.CharField(max_length=120)),
                ('comments', models.TextField(verbose_name='')),
                ('doctor', models.ManyToManyField(to='healthcareweb.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('doctors', models.ManyToManyField(through='healthcareweb.DoctorSpecialization', to='healthcareweb.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcareweb.Specialization'),
        ),
    ]
